const en = {
  app_name: 'Enatega Deliveries Rider App',
  welcome_title: 'Rider Workspace',
  welcome_subtitle: 'Theme, localization, and reusable base components are ready.',
  change_theme: 'Switch theme',
  change_language: 'Switch language',
  current_theme: 'Theme mode: {{mode}}',
  current_language: 'Language: {{language}}',
  auth_title: 'Enter Your Credentials to login',
  auth_subtitle: "We'll check if you have an account",
  auth_email_placeholder: 'Email',
  auth_password_placeholder: 'Password',
  auth_email_required: 'Email is required',
  auth_email_invalid: 'Please enter a valid email',
  auth_password_required: 'Password is required',
  auth_login: 'Login',
  auth_login_loading: 'Logging in...',
  auth_logout: 'Log Out',
  auth_logout_loading: 'Logging out...',

  nav_home: 'Home',
  nav_wallet: 'Wallet',
  nav_earnings: 'Earnings',
  nav_profile: 'Profile',
  earnings_recent_activity: 'Recent Activity',
  earnings_see_more: 'See More',
  earnings_total_earning: 'Total Earning',
  earnings_total_earnings: 'Total Earnings',
  earnings_hours: 'Hours',
  earnings_deliveries: 'Deliveries',
  earnings_deliveries_count: 'Deliveries({{count}})',
  earnings_hours_worked: 'Hours Worked',
  earnings_tips: 'Tips',
  earnings_summary: 'Summary',
  earnings_empty_title: 'No recent activity',
  earnings_empty_subtitle: 'Your earnings activity will appear here.',
  earnings_deliveries_empty_title: 'No deliveries found',
  earnings_deliveries_empty_subtitle: 'Completed deliveries for this date will appear here.',
  wallet_current_balance: 'Current Balance',
  wallet_withdraw_now: 'Withdraw Now',
  wallet_recent_transactions: 'Recent Transactions',
  wallet_no_transactions: 'No transactions found',
  wallet_available_amount: 'Available Amount',
  wallet_enter_amount: 'Enter Amount',
  wallet_confirm_withdraw: 'Confirm Withdraw',
  wallet_withdraw_success_title: 'Your request for withdrawal has been submitted',
  wallet_withdraw_success_subtitle: 'Usually it takes 1-2 business days',
  wallet_withdraw_invalid: 'Enter a valid withdrawal amount',
  wallet_withdraw_insufficient: 'Withdrawal amount exceeds your available balance',
  wallet_withdraw_pending: 'You already have a pending withdrawal request',
  wallet_withdraw_failed: 'Unable to submit withdrawal request',
  wallet_pending_request: 'Pending Withdrawal Request',
  profile_name: 'John Smith',
  profile_id: 'ID-7853',
  profile_driving_license: 'Driving License',
  profile_vehicle_plate: 'Vehicle Plate',
  profile_add: 'Add',
  profile_missing_data: 'Missing Data',
  profile_other_information: 'Other information',
  profile_email: 'Email',
  profile_email_value: 'JohnSmith@gmail.com',
  profile_password: 'Password',
  profile_password_value: '**********',
  profile_change: 'Change',
  profile_mobile_number: 'Mobile Number',
  profile_mobile_number_value: '+61-123-456-789',
  profile_plate_no: 'Plate No',
  profile_plate_no_value: 'GXR 4907',
  profile_license_no: 'License No',
  profile_license_no_value: '358247415445651',
  profile_license_expiry_date: 'License Expiry Date',
  profile_license_expiry_date_value: '29-12-2025',
  profile_add_registration_document: 'Add Resistration Document',
  profile_upload_document: 'Upload document',
  profile_take_photo: 'Take photo',
  profile_choose_from_gallery: 'Choose from gallery',
  profile_front_image: 'Front image',
  profile_back_image: 'Back image',
  profile_uploaded: 'Uploaded',
  profile_updating_documents: 'Updating...',
  profile_documents_updated: 'Documents updated successfully',
  profile_cancel: 'Cancel',
  profile_save: 'Save',
  profile_update_password_title: 'Update password',
  profile_update_password_subtitle: 'Set a new password and confirm it.',
  profile_old_password_placeholder: 'Enter Old Password',
  profile_new_password_placeholder: 'Enter New Password',
  profile_update_password_button: 'Update password',
  image_view_title: 'Image Preview',
  image_view_close: 'Close',
  image_zoom_in: 'Zoom +',
  image_zoom_out: 'Zoom -',
  image_zoom_reset: 'Reset',

  home_header_title: 'Orders',
  orders_ready: 'Ready',
  orders_pickup: 'Pickup',
  orders_completed: 'Completed',
  orders_new: 'New Orders',
  orders_processing: 'Processing',
  orders_delivered: 'Delivered',
  status_waiting_for_rider: 'Waiting for rider',
  status_waiting_to_pickup: 'Waiting to pickup',
  status_unknown: 'Unknown',
  order_assign_me: 'Assign me',
  order_assigning: 'Assigning...',
  order_assign_failed_fallback: 'Unable to assign this order right now.',
  order_assign_failed_title: 'Assignment failed',
  order_assign_failed_close: 'Close',
  offer_title: 'Incoming order offer',
  offer_order_id: 'Order ID',
  offer_pickup: 'Pickup',
  offer_amount: 'Order amount',
  offer_expires_in: 'Expires in',
  offer_accept: 'Accept',
  offer_decline: 'Decline',
  offer_unavailable_title: 'Offer unavailable',
  offer_unavailable_message: 'This offer expired or was taken by another rider.',
  manual_assignment_title: 'New order assigned',
  manual_assignment_message: 'This order is now in your active orders.',
  manual_assignment_dismiss: 'Dismiss',
  order_pick_order: 'Pick Order',
  order_delivered: 'Delivered',
  home_status: 'Status',
  home_order_status: 'Order Status',
  home_order_id: 'Order ID',
  home_store_name: 'Hardees Z-Block',
  home_pickup: 'Pickup Location',
  home_deliver: 'Deliver Location',
  home_view_on_map: 'View on map',
  home_payment_method: 'Payment Method',
  home_payment_status: 'Payment Status',
  home_order_amount: 'Order Amount',
  order_time: 'Order Time',
  home_not_paid: 'Not paid yet',
  home_comment: 'Comment',
  home_comment_text: 'Please bring it to my room',
  orders_empty: 'No orders available',
  home_not_approved_title: 'Not Approved',
  home_orders_hidden_unapproved: 'Your account is pending approval. Orders will appear once approved.',
  order_assigned_title: 'Assigned',
  order_navigate: 'Navigate',
  order_start_navigation: 'Start Navigation to Store',
  order_details_title: 'Order Details',
  order_items_and_quantity: 'ITEMS AND QUANTITY',
  order_price: 'PRICE',
  order_total: 'Total',
  order_delivery_progress: 'Delivery Progress',
  order_status_assigned: 'Assigned',
  order_status_heading_to_store: 'Heading to Store',
  order_status_arrived_at_store: 'Arrived at Store',
  order_status_waiting_for_order: 'Waiting for Order',
  order_status_picked_up: 'Picked Up',
  order_status_out_for_delivery: 'Out for Delivery',
  order_status_arrived_at_customer: 'Arrived at Customer',
  order_status_delivered: 'Delivered',
  order_status_failed: 'Failed',
  order_status_desc_assigned: 'Order has been assigned to rider',
  order_status_desc_heading_to_store: 'Rider is on the way to store',
  order_status_desc_arrived_at_store: 'Rider has arrived at the store',
  order_status_desc_waiting_for_order: 'Rider is waiting for the order',
  order_status_desc_picked_up: 'Rider has picked up the order',
  order_status_desc_out_for_delivery: 'Order is on the way to customer',
  order_status_desc_arrived_at_customer: 'Rider has arrived at customer location',
  order_status_desc_delivered: 'Order has been delivered',
  order_status_desc_failed: 'Order delivery failed',
  order_status_update_to: 'Update to',
  order_status_updating: 'Updating...',
  order_step: 'Step',
  order_next: 'Next: {{status}}',
  order_view_timeline: 'View full timeline',
  order_hide_timeline: 'Hide timeline',
  order_alert_store_preparing_title: 'Store is preparing the order',
  order_alert_store_preparing_desc: 'Pickup will be enabled once the store marks it ready.',
  order_alert_ready_pickup_title: 'Order is ready for pickup',
  order_waiting_for_order_disabled: 'Waiting for Order...',
  order_ready_next_job: 'Ready for Next job?',
  order_pick_next_order: 'Pick Next Order',
  order_done_for_today: 'I’m done for today',
  order_well_done_rider: 'Well Done Rider',
  order_delivered_message: 'Order number {{code}} Delivered',
  order_chat_default_name: 'Customer',
  chat_no_messages: 'No messages yet',
  chat_empty_hint: 'Start the conversation when you are ready.',
  chat_enter_concern: 'Enter your concern',
  chat_send: 'Send',
  chat_sending: 'Sending...',
  chat_support_title: 'Support chat',
  chat_send_not_available: 'Chat is not available for this order yet.',
  chat_contact_restaurant: 'Contact Restaurant',
  chat_order_number: 'Order number:',
  chat_reply_customer: 'Send a reply',

  menu_availability: 'Availability',
  menu_available: 'Available',
  menu_unavailable: 'Unavailable',
  menu_language: 'Language',
  menu_vehicle_type: 'Vehicle Type',
  menu_bank_management: 'Bank Management',
  menu_work_schedule: 'Work schedule',
  menu_profile: 'Profile',
  menu_privacy_policy: 'Privacy Policy',
  menu_about_us: 'About Us',
  menu_help: 'Help',
  menu_logout: 'Logout',
  vehicle_type_bicycle: 'Bicycle',
  vehicle_type_motorcycle: 'Motorcycle',
  vehicle_type_car: 'Car',
  vehicle_type_truck: 'Truck',
  vehicle_type_update_button: 'Update Vehicle',
  vehicle_type_updating_button: 'Updating...',
  bank_currency_label: 'Currency',
  bank_currency_value: 'EUR',
  bank_holder_name_label: 'Full Name of the Bank Account Holder',
  bank_holder_name_value: 'Gabriel Gutkowski',
  bank_iban_label: 'IBAN / Swift / BSB',
  bank_iban_value: 'IT25M0680218128171X4075J102',
  bank_account_number_label: 'Account Number',
  bank_account_number_value: '3254465164614411',
  bank_confirm_button: 'Confirm',
  bank_bank_name_label: 'Bank Name',
  bank_account_code_label: 'Account Code',
  bank_required_field: 'This field is required',
  bank_updating_button: 'Updating...',
  work_schedule_mon: 'MON',
  work_schedule_tue: 'TUE',
  work_schedule_wed: 'WED',
  work_schedule_thu: 'THU',
  work_schedule_fri: 'FRI',
  work_schedule_sat: 'SAT',
  work_schedule_sun: 'SUN',
  work_schedule_update_button: 'Update Schedule',
  work_schedule_updating_button: 'Updating...',
  work_schedule_required_field: 'Please enter open and close time for active days.',
  work_schedule_add_slot: 'Add slot',
  language_option_english: 'English',
  language_option_francais: 'Francais',
  language_option_japanese: 'Japanese',
  language_option_chinese: 'Chinese',
  language_option_deutsche: 'Deutsche',
  language_option_arabic: 'Arabic',
  language_update_button: 'Update Language',
};

export default en;
