const fr = {
  app_name: 'Enatega Deliveries Rider App',
  welcome_title: 'Espace livreur',
  welcome_subtitle: 'Theme, localisation et composants de base reutilisables sont prets.',
  change_theme: 'Changer le thème',
  change_language: 'Changer la langue',
  current_theme: 'Mode de thème: {{mode}}',
  current_language: 'Langue: {{language}}',
  auth_title: 'Entrez vos identifiants pour vous connecter',
  auth_subtitle: 'Nous verifierons si vous avez un compte',
  auth_email_placeholder: 'Email',
  auth_password_placeholder: 'Mot de passe',
  auth_email_required: "L'email est requis",
  auth_email_invalid: 'Veuillez saisir un email valide',
  auth_password_required: 'Le mot de passe est requis',
  auth_login: 'Se connecter',
  auth_login_loading: 'Connexion...',
  auth_logout: 'Se deconnecter',
  auth_logout_loading: 'Deconnexion...',

  nav_home: 'Accueil',
  nav_wallet: 'Portefeuille',
  nav_earnings: 'Gains',
  nav_profile: 'Profil',
  earnings_recent_activity: 'Activite recente',
  earnings_see_more: 'Voir plus',
  earnings_total_earning: 'Gain total',
  earnings_total_earnings: 'Gains totaux',
  earnings_hours: 'Heures',
  earnings_deliveries: 'Livraisons',
  earnings_deliveries_count: 'Livraisons({{count}})',
  earnings_hours_worked: 'Heures travaillees',
  earnings_tips: 'Pourboires',
  earnings_summary: 'Resume',
  earnings_empty_title: 'Aucune activite recente',
  earnings_empty_subtitle: 'Votre activite de gains apparaitra ici.',
  earnings_deliveries_empty_title: 'Aucune livraison trouvee',
  earnings_deliveries_empty_subtitle: 'Les livraisons terminees pour cette date apparaitront ici.',
  wallet_current_balance: 'Solde actuel',
  wallet_withdraw_now: 'Retirer maintenant',
  wallet_recent_transactions: 'Transactions recentes',
  wallet_no_transactions: 'Aucune transaction trouvee',
  wallet_available_amount: 'Montant disponible',
  wallet_enter_amount: 'Entrer le montant',
  wallet_confirm_withdraw: 'Confirmer le retrait',
  wallet_withdraw_success_title: 'Votre demande de retrait a ete soumise',
  wallet_withdraw_success_subtitle: 'Habituellement, cela prend 1 a 2 jours ouvrables',
  wallet_withdraw_invalid: 'Entrez un montant de retrait valide',
  wallet_withdraw_insufficient: 'Le montant depasse votre solde disponible',
  wallet_withdraw_pending: 'Vous avez deja une demande de retrait en attente',
  wallet_withdraw_failed: 'Impossible de soumettre la demande de retrait',
  wallet_pending_request: 'Demande de retrait en attente',
  profile_name: 'John Smith',
  profile_id: 'ID-7853',
  profile_driving_license: 'Permis de conduire',
  profile_vehicle_plate: 'Plaque du vehicule',
  profile_add: 'Ajouter',
  profile_missing_data: 'Donnees manquantes',
  profile_other_information: 'Autres informations',
  profile_email: 'Email',
  profile_email_value: 'JohnSmith@gmail.com',
  profile_password: 'Mot de passe',
  profile_password_value: '**********',
  profile_change: 'Changer',
  profile_mobile_number: 'Numero de mobile',
  profile_mobile_number_value: '+61-123-456-789',
  profile_plate_no: 'Numero de plaque',
  profile_plate_no_value: 'GXR 4907',
  profile_license_no: 'Numero de permis',
  profile_license_no_value: '358247415445651',
  profile_license_expiry_date: "Date d'expiration du permis",
  profile_license_expiry_date_value: '29-12-2025',
  profile_add_registration_document: "Ajouter le document d'immatriculation",
  profile_upload_document: 'Telecharger le document',
  profile_take_photo: 'Prendre une photo',
  profile_choose_from_gallery: 'Choisir depuis la galerie',
  profile_front_image: 'Image avant',
  profile_back_image: 'Image arriere',
  profile_uploaded: 'Telecharge',
  profile_updating_documents: 'Mise a jour...',
  profile_documents_updated: 'Documents mis a jour avec succes',
  profile_cancel: 'Annuler',
  profile_save: 'Enregistrer',
  profile_update_password_title: 'Mettre a jour le mot de passe',
  profile_update_password_subtitle: 'Definissez un nouveau mot de passe et confirmez-le.',
  profile_old_password_placeholder: 'Entrer le mot de passe actuel',
  profile_new_password_placeholder: 'Entrer le nouveau mot de passe',
  profile_update_password_button: 'Mettre a jour le mot de passe',
  image_view_title: 'Apercu image',
  image_view_close: 'Fermer',
  image_zoom_in: 'Zoom +',
  image_zoom_out: 'Zoom -',
  image_zoom_reset: 'Reinitialiser',

  home_header_title: 'Commandes',
  orders_ready: 'Pretes',
  orders_pickup: 'Collecte',
  orders_completed: 'Terminees',
  orders_new: 'Nouvelles',
  orders_processing: 'En cours',
  orders_delivered: 'Livrees',
  status_waiting_for_rider: 'En attente du livreur',
  status_waiting_to_pickup: 'En attente de ramassage',
  status_unknown: 'Inconnu',
  order_assign_me: "M'assigner",
  order_assigning: 'Assignation...',
  order_assign_failed_fallback: "Impossible d'assigner cette commande pour le moment.",
  order_assign_failed_title: "Echec de l'assignation",
  order_assign_failed_close: 'Fermer',
  offer_title: 'Nouvelle offre de commande',
  offer_order_id: 'ID de commande',
  offer_pickup: 'Collecte',
  offer_amount: 'Montant de la commande',
  offer_expires_in: 'Expire dans',
  offer_accept: 'Accepter',
  offer_decline: 'Refuser',
  offer_unavailable_title: 'Offre indisponible',
  offer_unavailable_message: "Cette offre a expire ou a ete prise par un autre livreur.",
  manual_assignment_title: 'Nouvelle commande assignee',
  manual_assignment_message: 'Cette commande figure maintenant dans vos commandes actives.',
  manual_assignment_dismiss: 'Fermer',
  order_pick_order: 'Prendre la commande',
  order_delivered: 'Livree',
  home_status: 'Statut',
  home_order_status: 'Statut de commande',
  home_order_id: 'ID Commande',
  home_store_name: 'Hardees Z-Block',
  home_pickup: 'Recuperer commande',
  home_deliver: 'Livrer commande',
  home_view_on_map: 'Voir sur la carte',
  home_payment_method: 'Methode de paiement',
  home_payment_status: 'Statut du paiement',
  home_order_amount: 'Montant de commande',
  order_time: 'Heure de commande',
  home_not_paid: 'Non paye',
  home_comment: 'Commentaire',
  home_comment_text: 'Veuillez le livrer a ma chambre',
  orders_empty: 'Aucune commande disponible',
  home_not_approved_title: 'Non approuve',
  home_orders_hidden_unapproved: 'Votre compte est en attente d approbation. Les commandes apparaitront une fois approuve.',
  order_assigned_title: 'Assigne',
  order_navigate: 'Naviguer',
  order_start_navigation: 'Commencer la navigation vers le magasin',
  order_details_title: 'Details de commande',
  order_items_and_quantity: 'ARTICLES ET QUANTITE',
  order_price: 'PRIX',
  order_total: 'Total',
  order_delivery_progress: 'Progression de livraison',
  order_status_assigned: 'Assigne',
  order_status_heading_to_store: 'En route vers le magasin',
  order_status_arrived_at_store: 'Arrive au magasin',
  order_status_waiting_for_order: 'En attente de commande',
  order_status_picked_up: 'Recupere',
  order_status_out_for_delivery: 'En cours de livraison',
  order_status_arrived_at_customer: 'Arrive chez le client',
  order_status_delivered: 'Livre',
  order_status_failed: 'Echoue',
  order_status_desc_assigned: 'La commande a ete assignee au livreur',
  order_status_desc_heading_to_store: 'Le livreur est en route vers le magasin',
  order_status_desc_arrived_at_store: 'Le livreur est arrive au magasin',
  order_status_desc_waiting_for_order: 'Le livreur attend la commande',
  order_status_desc_picked_up: 'Le livreur a recupere la commande',
  order_status_desc_out_for_delivery: 'La commande est en route vers le client',
  order_status_desc_arrived_at_customer: 'Le livreur est arrive chez le client',
  order_status_desc_delivered: 'La commande a ete livree',
  order_status_desc_failed: 'La livraison a echoue',
  order_status_update_to: 'Mettre a jour vers',
  order_status_updating: 'Mise a jour...',
  order_step: 'Etape',
  order_next: 'Suivant: {{status}}',
  order_view_timeline: 'Voir la chronologie',
  order_hide_timeline: 'Masquer la chronologie',
  order_alert_store_preparing_title: 'Le magasin prepare la commande',
  order_alert_store_preparing_desc: 'Le retrait sera active lorsque le magasin la marquera prete.',
  order_alert_ready_pickup_title: 'La commande est prete pour le retrait',
  order_waiting_for_order_disabled: 'En attente de commande...',
  order_ready_next_job: 'Pret pour la prochaine mission ?',
  order_pick_next_order: 'Prendre la prochaine commande',
  order_done_for_today: 'J ai termine pour aujourd hui',
  order_well_done_rider: 'Bravo Rider',
  order_delivered_message: 'Commande {{code}} livree',
  order_chat_default_name: 'Client',
  chat_no_messages: 'Aucun message pour le moment',
  chat_empty_hint: 'Commencez la conversation quand vous etes pret.',
  chat_enter_concern: 'Saisissez votre message',
  chat_send: 'Envoyer',
  chat_sending: 'Envoi...',
  chat_support_title: 'Discussion support',
  chat_send_not_available: 'Le chat n est pas encore disponible pour cette commande.',
  chat_contact_restaurant: 'Contacter le restaurant',
  chat_order_number: 'Numero de commande:',
  chat_reply_customer: 'Send a reply',

  menu_availability: 'Disponibilite',
  menu_available: 'Disponible',
  menu_unavailable: 'Indisponible',
  menu_language: 'Langue',
  menu_vehicle_type: 'Type de vehicule',
  menu_bank_management: 'Gestion bancaire',
  menu_work_schedule: 'Horaire de travail',
  menu_profile: 'Profil',
  menu_privacy_policy: 'Politique de confidentialite',
  menu_about_us: 'A propos',
  menu_help: 'Aide',
  menu_logout: 'Se deconnecter',
  vehicle_type_bicycle: 'Velo',
  vehicle_type_motorcycle: 'Moto',
  vehicle_type_car: 'Voiture',
  vehicle_type_truck: 'Camion',
  vehicle_type_update_button: 'Mettre a jour le vehicule',
  vehicle_type_updating_button: 'Mise a jour...',
  bank_currency_label: 'Devise',
  bank_currency_value: 'EUR',
  bank_holder_name_label: 'Nom complet du titulaire du compte bancaire',
  bank_holder_name_value: 'Gabriel Gutkowski',
  bank_iban_label: 'IBAN / Swift / BSB',
  bank_iban_value: 'IT25M0680218128171X4075J102',
  bank_account_number_label: 'Numero de compte',
  bank_account_number_value: '3254465164614411',
  bank_confirm_button: 'Confirmer',
  bank_bank_name_label: 'Nom de la banque',
  bank_account_code_label: 'Code du compte',
  bank_required_field: 'Ce champ est obligatoire',
  bank_updating_button: 'Mise a jour...',
  work_schedule_mon: 'LUN',
  work_schedule_tue: 'MAR',
  work_schedule_wed: 'MER',
  work_schedule_thu: 'JEU',
  work_schedule_fri: 'VEN',
  work_schedule_sat: 'SAM',
  work_schedule_sun: 'DIM',
  work_schedule_update_button: 'Mettre a jour le planning',
  work_schedule_updating_button: 'Mise a jour...',
  work_schedule_required_field: 'Veuillez saisir les heures d ouverture et de fermeture pour les jours actifs.',
  work_schedule_add_slot: 'Ajouter un slot',
  language_option_english: 'English',
  language_option_francais: 'Francais',
  language_option_japanese: 'Japanese',
  language_option_chinese: 'Chinese',
  language_option_deutsche: 'Deutsche',
  language_option_arabic: 'Arabic',
  language_update_button: 'Mettre a jour la langue',
};

export default fr;
